version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9

    working_directory: ~/mouworks.github.io
    environment:
      - SOURCE_BRANCH: src
      - TARGET_BRANCH: master
    steps:
      - add_ssh_keys:
          fingerprints:
            # This key require additional setup @circleCI
            - "8d:ae:2c:a0:8b:4b:c0:49:d0:5e:d9:f0:d3:5c:8c:7e"
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Vuepress
          command: sudo yarn global add vuepress

      - deploy:
          name: Deploy (Push back to github)
          command: |
            mv .circleci/circleci_deploy.sh .
            ./circleci_deploy.sh
workflows:
  version: 2.1
  build_and_auto_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - src